config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

    # devise_for :users
    root to: "home#index"
    resources :input

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/input.rb
class Input < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    render
  end
end

app/controllers/input_controller.rb
# require 'pycall/import'
# include PyCall::Import
# pyfrom :'sklearn.model_selection', import: :train_test_split
# PyCall.import_module("pandas")
# PyCall.import_module("numpy")
class InputController < ApplicationController

  def index
  end

  def new
    @input = Input.new
  end

  def create

    @input = Input.new(input_params)

    if @input.valid?
      # Ml.predict_prices(@input)
      @input.save
      redirect_to @input, notice: 'Successfully created'
    else
      render new
    end
  end

  private

  def input_params
    params.require(:input)
          .permit(
            :city,
            :area,
            :bedrooms,
            :bathrooms,
            :preference,
            :property_type
          )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/input_helper.rb
module InputHelper
end

app/views/home/index.html.erb
<h1>Market Value Analysis</h1>
<% if user_signed_in? %>
  <div> Welcome <%= current_user.email %> </div>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  <%= link_to "Prediction", new_input_path(@input)%>
<% else %>
  <%= link_to "Sign in", new_user_session_path %>
<% end %>

app/views/input/index.html.erb
<h1>Welcome!</h1>

<%= button_to "Enter Details", input_info_path%>

app/views/input/info.html.erb
<h1> Hello!!</h1>
<h2>Price</h2>

app/views/input/new.html.erb
<%= form_with(model: @input, local: true, url:input_index_path ) do |form| %>

  <h1> Enter Details</h1>
  <div class="field">
    <%= form.label :City, class: 'form-label' %>
    <%= form.text_field :City, id: 'post-title', class: "form-control"%>
  </div>

  <div class="field">
    <%= form.label :Area, class: 'form-label' %>
    <%= form.text_field :Area, id: 'post-title', class: "form-control"%>
  </div>

  <div class="field">
    <%= form.label :bedrooms, class: 'form-label' %>
    <%= form.text_field :bedrooms, id: 'post-title', class: "form-control"%>
  </div>

  <div class="field">
    <%= form.label :bathrooms, class: 'form-label' %>
    <%= form.text_field :bathrooms, id: 'post-title', class: "form-control"%>
  </div>


  <fieldset class="rating">
    <%= form.label :Preference, class: 'form-label' %><br>
    <%= form.radio_button :Preference, 'Sale' , class: 'form-check-input'%> <%= form.label("Sale", class: 'form-check-label') %>
    <%= form.radio_button :Preference, 'Rent',  class: 'form-check-input'%> <%= form.label("Rent", class: 'form-check-label') %>
</fieldset>

  <fieldset class="rating">
    <%= form.label :Property_type, class: 'form-label' %><br>
    <%= form.radio_button :Property_type, 'Residential Land' , class: 'form-check-input'%> <%= form.label("Land", class: 'form-check-label') %>
    <%= form.radio_button :Property_type, 'Residential Apartment',  class: 'form-check-input'%> <%= form.label("Apartment", class: 'form-check-label') %>
  </fieldset>


  <div class="actions btn">
    <%= form.submit "Predict" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>